= Next generation MicrositeMaster Theme

This repository contains a theme for DB microsites. It's used for internal sites, but for example also for the https://github.com/dbsystel/tech-stories[DB Systel Tech Stories].

== Local development

Make sure you have wget installed.

NOTE: The arch -x86_64 statements force mac os to use rosetta in order to emulate an x64 environment, which seems to be needed for jbake to work properly. You can omit this when working on a windows machine.

.prepare environment
----
arch -x86_64 ./dtcw getJava
----
To quickly build the documentation with a docker container, use this
[source, shell script]
----
arch -x86_64 ./dtcw docker generateSite
arch -x86_64 ./dtcw docker previewSite
arch -x86_64 ./dtcw local generateSite
arch -x86_64 ./dtcw local previewSite
----

== Publish new theme

in file `build.gradle`, go to `zipTheme` task and incement version number.
run `./gradlew zipTheme`. push the new file.

== Contributions

If you have comments or suggestions for improvements, please open an issue. See link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] for more details.

== Licensing, copyrights, and trademarks

=== License and copyright

The majority of this project is licensed under link:LICENSE.txt[Apache-2.0]. This is the default inbound license for contributions. Copyright 2023 by DB Systel GmbH.

Please note that some parts are subject to trademarks and proprietary licenses. See below for details.

=== Deutsche Bahn brand

The usage of Deutsche Bahn brand and trademarks are bound to clear guidelines and restrictions even when being used with the code that we're providing with this product. Deutsche Bahn fully reserves all rights and ownership regarding the Deutsche Bahn brand, even though that we're providing the code free to use and release the most part under the Apache 2.0 license. Please have a look at our link:https://marketingportal.extranet.deutschebahn.com/[brand portal] for any further questions and whom to contact on any brand issues. As these assets and visual guidelines are retrieved from our Deutsche Bahn Marketingportal, you'll agree with the link:https://marketingportal.extranet.deutschebahn.com/marketingportal/Nutzungsbedingungen-9702684["Allgemeine Nutzungsbedingungen für das DB-Marketingportal" (german)] in case of using them.

For any usage outside of Deutsche Bahn websites and applications you must remove or replace any Deutsche Bahn brand and design assets as well as protected characteristics and trademarks.

This especially relates to the files in the directories `/src/site/assets/fonts` and `/src/site/assets/images`.

The fonts in the directory `/src/site/assets/fonts` can only be used in the context of your work at Deutsche Bahn or to fulfill orders and/or services, that are bound to contracts with Deutsche Bahn. Any other usage especially for private purposes or unintended third parties is not allowed. See the https://marketingportal.extranet.deutschebahn.com/marketingportal/Lizenzvereinbarung-ueber-die-Nutzung-der-DB-Type-Schriftenfamilie-9693166[license] for details.

=== Credits

A large part of the design and assets is kindly borrowed by link:https://github.com/db-ui[DB UI]. If you intend to build a website in the Deutsche Bahn theme, please refer to this marvellous Open Source project.

This project makes use of a number of third-party Open Source projects that may be be under different licenses. We would like to thank them for their valuable contributions!

* Asciidoctor (MIT)
* Bootstrap (MIT)
* docToolchain (MIT)
* Font Awesome (CC-BY-4.0, OFL-1.1)
* Glyphicons Halflings via Bootstrap (CC-BY-3.0, MIT)
* Gradle (Apache-2.0)
* jQuery (MIT)
* Lunr.js (MIT)
* Popper.js (MIT)
