name: Release themes as archives

on:
  push:
    # Runs on semver-tagged releases
    tags:
      - "v*.*.*"

jobs:
  zip_themes:
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    strategy:
      matrix:
        # List of theme directories that shall be included
        directory: [siteTheme-Bahn-ng]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Zip the theme directory
        run: |
          cd ${{ matrix.directory }} && zip -r ../${{ matrix.directory }}-${{ github.ref_name }}.zip .
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: ${{ matrix.directory }}
          path: ${{ matrix.directory }}-${{ github.ref_name }}.zip
          retention-days: 1

  make_release:
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    needs: zip_themes
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          path: artifacts
      - name: Create GitHub draft release with the zipped themes as assets
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090
        with:
          # Note: uses default github workflow token which needs write access configured
          files: artifacts/*/*
          draft: true
